/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import database.DatabaseConnection;
import model.Dokter;
import util.SessionManager;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Dit
 */
public class DokterDashboardFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DokterDashboardFrame.class.getName());

    /**
     * Creates new form DokterDashboardFrame
     */
    public DokterDashboardFrame() {
        initComponents();
        setLocationRelativeTo(null);
        loadStatistics();      // Load angka statistik
        loadPatientQueue();// Load tabel antrean pasien
    }
    
    private void loadStatistics() {
        try {
            Connection conn = DatabaseConnection.getConnection();

            String sql = "SELECT "
                    + "SUM(CASE WHEN status_reservasi IN ('CHECK_IN', 'ASSIGNED') THEN 1 ELSE 0 END) as waiting, "
                    + "SUM(CASE WHEN status_reservasi = 'DIPERIKSA' THEN 1 ELSE 0 END) as examination, "
                    + "SUM(CASE WHEN status_reservasi IN ('SELESAI', 'LUNAS') AND DATE(tanggal) = CURDATE() THEN 1 ELSE 0 END) as completed "
                    + "FROM reservasi";

            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                tfWaitingPatients.setText(String.valueOf(rs.getInt("waiting")));
                tfExamination.setText(String.valueOf(rs.getInt("examination")));
                tfCompleateToday.setText(String.valueOf(rs.getInt("completed")));
            }

            // Set non-editable
            tfWaitingPatients.setEditable(false);
            tfExamination.setEditable(false);
            tfCompleateToday.setEditable(false);

        } catch (SQLException e) {
            System.err.println("[DokterDashboard] Error load statistics: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    private void loadPatientQueue() {
        try {
            Connection conn = DatabaseConnection.getConnection();

            // Query: Ambil reservasi yang statusnya siap diperiksa
            String sql = "SELECT r.id_reservasi, u.nama_lengkap, h.nama_hewan, h.jenis, "
                    + "COALESCE(l.nama_layanan, 'General Checkup') as layanan, "
                    + "DATE(r.tanggal) as tanggal, TIME(r.tanggal) as waktu, r.status_reservasi "
                    + "FROM reservasi r "
                    + "JOIN hewan h ON r.id_hewan = h.id_hewan "
                    + "JOIN customer c ON r.id_customer = c.id_customer "
                    + "JOIN users u ON c.id_user = u.id_user "
                    + "LEFT JOIN pemeriksaan p ON r.id_reservasi = p.id_reservasi "
                    + "LEFT JOIN layanan l ON p.id_layanan = l.id_layanan "
                    + "WHERE r.status_reservasi IN ('CHECK_IN', 'ASSIGNED', 'DIPERIKSA') "
                    + "ORDER BY r.tanggal ASC";

            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            DefaultTableModel model = new DefaultTableModel(
                    new String[]{"Res. ID", "Owner", "Pet Name", "Type", "Service", "Date", "Time", "Status"}, 0
            );

            while (rs.next()) {
                model.addRow(new Object[]{
                    "R-" + rs.getInt("id_reservasi"),
                    rs.getString("nama_lengkap"),
                    rs.getString("nama_hewan"),
                    rs.getString("jenis"),
                    rs.getString("layanan"),
                    rs.getString("tanggal"),
                    rs.getString("waktu"),
                    rs.getString("status_reservasi")
                });
            }

            jTable1.setModel(model);

        } catch (SQLException e) {
            System.err.println("[DokterDashboard] Error load queue: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        lblNama2 = new javax.swing.JLabel();
        BtnLogout = new javax.swing.JButton();
        tfWaitingPatients = new javax.swing.JTextField();
        lblNama3 = new javax.swing.JLabel();
        tfExamination = new javax.swing.JTextField();
        lblNama4 = new javax.swing.JLabel();
        tfCompleateToday = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnStartExamination = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblNama2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNama2.setText("Waiting Patients:");

        BtnLogout.setText("Logout");
        BtnLogout.addActionListener(this::BtnLogoutActionPerformed);

        tfWaitingPatients.setText("jTextField1");

        lblNama3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNama3.setText("in Examination:");

        tfExamination.setText("jTextField1");

        lblNama4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNama4.setText("Compleate Today:");

        tfCompleateToday.setText("jTextField1");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblNama2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfWaitingPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lblNama3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfExamination, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(lblNama4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCompleateToday, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addComponent(BtnLogout)
                .addGap(17, 17, 17))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNama4))
                        .addComponent(tfCompleateToday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfExamination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNama3))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtnLogout)
                        .addComponent(tfWaitingPatients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNama2)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Patient Queue"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Res, ID", "Owner", "Pet Name", "Type", "Service", "Date", "Time", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnStartExamination.setText("Start Examination");
        btnStartExamination.addActionListener(this::btnStartExaminationActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 984, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStartExamination))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(btnStartExamination)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(558, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(67, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Patien Queue");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogoutActionPerformed
        // TODO add your handling code here:
        // 1. Logout dari SessionManager
        SessionManager.getInstance().logout();

        // 2. Tampilkan pesan
        javax.swing.JOptionPane.showMessageDialog(this, "Anda telah logout!");

        // 3. Tutup dashboard
        this.dispose();

        // 4. Buka LoginFrame
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_BtnLogoutActionPerformed

    private void btnStartExaminationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartExaminationActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                    "Pilih pasien yang akan diperiksa terlebih dahulu!",
                    "Warning",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Ambil ID Reservasi dari tabel (format "R-1" -> ubah jadi int 1)
        String resId = jTable1.getValueAt(selectedRow, 0).toString();
        int idReservasi = Integer.parseInt(resId.replace("R-", ""));

        // Update status ke DIPERIKSA di database
        try {
            Connection conn = DatabaseConnection.getConnection();
            String sql = "UPDATE reservasi SET status_reservasi = 'DIPERIKSA' WHERE id_reservasi = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, idReservasi);
            ps.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }

        // Buka FormPemeriksaanFrame
        FormPemeriksaanFrame form = new FormPemeriksaanFrame(idReservasi);

        // Efek pop-up (seperti yang kita lakukan di modul Staff)
        form.setLocationRelativeTo(this);
        form.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                loadStatistics();      // Refresh statistik
                loadPatientQueue();    // Refresh tabel antrean
            }
        });

        form.setVisible(true);
    }//GEN-LAST:event_btnStartExaminationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DokterDashboardFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogout;
    private javax.swing.JButton btnStartExamination;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblNama2;
    private javax.swing.JLabel lblNama3;
    private javax.swing.JLabel lblNama4;
    private javax.swing.JTextField tfCompleateToday;
    private javax.swing.JTextField tfExamination;
    private javax.swing.JTextField tfWaitingPatients;
    // End of variables declaration//GEN-END:variables
}
