/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import database.DatabaseConnection;
import model.Customer;
import util.SessionManager;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author syahrilfarhan
 */
public class FormTambahHewan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTambahHewan.class.getName());

    /**
     * Creates new form FormTambahHewan
     */
    public FormTambahHewan() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnSavePet = new javax.swing.JButton();
        tfPetname = new javax.swing.JTextField();
        tfPettype = new javax.swing.JTextField();
        tfPetage = new javax.swing.JTextField();
        btnCancel = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pet Data"));

        btnSavePet.setText("Save Pet");
        btnSavePet.addActionListener(this::btnSavePetActionPerformed);

        tfPetname.setBorder(javax.swing.BorderFactory.createTitledBorder("Pet Name:"));

        tfPettype.setBorder(javax.swing.BorderFactory.createTitledBorder("Pet Type:"));

        tfPetage.setBorder(javax.swing.BorderFactory.createTitledBorder("Age (years)"));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfPetname, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(tfPettype)
                    .addComponent(tfPetage))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnSavePet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(tfPetname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfPettype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfPetage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSavePet)
                    .addComponent(btnCancel))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.getAccessibleContext().setAccessibleName("Pet Data");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSavePetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePetActionPerformed
        // TODO add your handling code here:
        String petName = tfPetname.getText().trim();
        String petType = tfPettype.getText().trim();
        String petAgeText = tfPetage.getText().trim();

        if (petName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pet name must be filled!", "Warning", JOptionPane.WARNING_MESSAGE);
            tfPetname.requestFocus();  
            return;
        }

        if (petType.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pet type must be filled!", "Warning", JOptionPane.WARNING_MESSAGE);
            tfPettype.requestFocus(); 
            return;
        }

        if (petAgeText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pet age must be filled!", "Warning", JOptionPane.WARNING_MESSAGE);
            tfPetage.requestFocus();  
            return;
        }

        int petAge;
        try {
            petAge = Integer.parseInt(petAgeText);

            System.out.println("[DEBUG] Umur yang diinput: " + petAge);

            if (petAge < 0 || petAge > 50) {
                System.out.println("[WARNING] Umur di luar range: " + petAge);
                JOptionPane.showMessageDialog(this,
                        "Age must be between 0 and 50 years!\nYou entered: " + petAge,
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                tfPetage.requestFocus();
                return;  
            }
        } catch (NumberFormatException e) {
            System.out.println("[ERROR] Bukan angka: " + petAgeText);
            JOptionPane.showMessageDialog(this, "Age must be a valid number!", "Error", JOptionPane.ERROR_MESSAGE);
            tfPetage.requestFocus();
            return;
        }

        try {
            Customer customer = (Customer) SessionManager.getInstance().getCurrentUser();

            if (customer == null) {
                JOptionPane.showMessageDialog(this, "User not logged in!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Connection conn = DatabaseConnection.getConnection();

            String sqlGetCustomerId = "SELECT c.id_customer FROM customer c "
                    + "JOIN users u ON c.id_user = u.id_user "
                    + "WHERE u.username = ?";
            PreparedStatement psGetId = conn.prepareStatement(sqlGetCustomerId);
            psGetId.setString(1, customer.getUsername());
            ResultSet rs = psGetId.executeQuery();

            int idCustomer = 0;
            if (rs.next()) {
                idCustomer = rs.getInt("id_customer");
                System.out.println("[DEBUG] ID Customer dari database: " + idCustomer);
            } else {
                System.out.println("[ERROR] Customer tidak ditemukan di database!");
                JOptionPane.showMessageDialog(this, "Customer data not found in database!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Insert ke database
            String sql = "INSERT INTO hewan (id_customer, nama_hewan, jenis, umur) VALUES (?, ?, ?, ?)";
            PreparedStatement ps = conn.prepareStatement(sql);

            ps.setInt(1, idCustomer);  
            ps.setString(2, petName);
            ps.setString(3, petType);
            ps.setInt(4, petAge);

            System.out.println("[DEBUG] Insert hewan: " + petName + ", umur: " + petAge + ", id_customer: " + idCustomer);

            int rowsInserted = ps.executeUpdate();

            if (rowsInserted > 0) {
                System.out.println("[SUCCESS] Hewan berhasil ditambahkan!");
                JOptionPane.showMessageDialog(this, "Pet successfully added!", "Success", JOptionPane.INFORMATION_MESSAGE);

                tfPetname.setText("");
                tfPettype.setText("");
                tfPetage.setText("");

                this.dispose();
            }

        } catch (SQLException e) {
            System.err.println("[ERROR] Database error: " + e.getMessage());
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (Exception e) {
            System.err.println("[ERROR] " + e.getMessage());
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSavePetActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to cancel?",
                "Confirm Cancel",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new FormTambahHewan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCancel;
    private javax.swing.JButton btnSavePet;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField tfPetage;
    private javax.swing.JTextField tfPetname;
    private javax.swing.JTextField tfPettype;
    // End of variables declaration//GEN-END:variables
}
