/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import database.DatabaseConnection;
import model.DetailTransaksi;
import model.Obat;
import util.SessionManager;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dit
 */
public class FormPemeriksaanFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPemeriksaanFrame.class.getName());
    private int idReservasi;
    private List<DetailTransaksi> daftarResep;
    private double totalObat;
    
    /**
     * Creates new form FormPemeriksaanFrame
     */
    public FormPemeriksaanFrame(int idReservasi) {
        this.idReservasi = idReservasi;
        this.daftarResep = new ArrayList<>();
        this.totalObat = 0;
        initComponents();
        setLocationRelativeTo(null);
        loadPatientData();
        loadMedicinesToDropdown();
        setupTable();
        setupDeleteListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // ==========================================
    // LOGIKA: Load Data Pasien dari Database
    // ==========================================
    private void loadPatientData() {
        try {
            Connection conn = DatabaseConnection.getConnection();
            String sql = "SELECT r.id_reservasi, h.nama_hewan, h.jenis, h.umur, "
                    + "u.nama_lengkap, r.tanggal, l.nama_layanan "
                    + "FROM reservasi r "
                    + "JOIN hewan h ON r.id_hewan = h.id_hewan "
                    + "JOIN customer c ON r.id_customer = c.id_customer "
                    + "JOIN users u ON c.id_user = u.id_user "
                    + "LEFT JOIN pemeriksaan p ON r.id_reservasi = p.id_reservasi "
                    + "LEFT JOIN layanan l ON p.id_layanan = l.id_layanan "
                    + "WHERE r.id_reservasi = ?";

            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, idReservasi);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                tfUmurPet.setText(rs.getString("nama_hewan") + " (" + rs.getString("jenis") + ", " + rs.getInt("umur") + " yr)");
                tfReservationID1.setText("R-" + rs.getInt("id_reservasi"));
                tfOwner.setText(rs.getString("nama_lengkap"));
                tfService.setText(rs.getString("nama_layanan") != null ? rs.getString("nama_layanan") : "General Checkup");
                tfDate.setText(rs.getString("tanggal"));

                // Set non-editable
                tfUmurPet.setEditable(false);
                tfReservationID1.setEditable(false);
                tfOwner.setEditable(false);
                tfService.setEditable(false);
                tfDate.setEditable(false);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading patient data: " + e.getMessage());
        }
    }
    
    // ==========================================
    // LOGIKA: Load Obat ke Dropdown
    // ==========================================
    private void loadMedicinesToDropdown() {
        try {
            Connection conn = DatabaseConnection.getConnection();
            String sql = "SELECT id_obat, nama_obat, harga, stok FROM obat WHERE stok > 0 ORDER BY nama_obat";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            jComboBox1.removeAllItems();
            jComboBox1.addItem("-- Pilih Obat --");

            while (rs.next()) {
                int idObat = rs.getInt("id_obat");
                String namaObat = rs.getString("nama_obat");
                double harga = rs.getDouble("harga");
                int stok = rs.getInt("stok");
                String item = idObat + "|" + namaObat + " - Rp " + formatRupiah(harga) + " (Stok: " + stok + ")";
                jComboBox1.addItem(item);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading medicines: " + e.getMessage());
        }
    }
    
    // ==========================================
    // LOGIKA: Setup Tabel Resep
    // ==========================================
    private void setupTable() {
        jTable2.setModel(new DefaultTableModel(
                new String[]{"Medicine", "Qty", "Subtotal", "Del"}, 0
        ));
    }

    // ==========================================
    // ✅ BARU: Setup Listener untuk Tombol Delete
    // ==========================================
    private void setupDeleteListener() {
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = jTable2.rowAtPoint(evt.getPoint());
                int col = jTable2.columnAtPoint(evt.getPoint());

                if (col == 3 && row >= 0) { // Kolom "Del"
                    DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                    String namaObat = model.getValueAt(row, 0).toString();
                    int qty = Integer.parseInt(model.getValueAt(row, 1).toString());

                    // Hapus dari list
                    daftarResep.removeIf(d -> {
                        Obat o = (Obat) d.getObat();
                        return o != null && o.getNamaObat().equals(namaObat) && d.getQty() == qty;
                    });

                    // Hapus dari tabel
                    model.removeRow(row);

                    // Recalculate total
                    recalculateTotal();
                }
            }
        });
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfOwner = new javax.swing.JTextField();
        tfUmurPet = new javax.swing.JTextField();
        tfReservationID1 = new javax.swing.JTextField();
        tfService = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfDate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTADiagnosis = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTADiagnosis1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        tfServiceCost = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        tfQuantity = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfServisCostPerhitungan = new javax.swing.JTextField();
        tfMedicines = new javax.swing.JTextField();
        tfTotal = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Patient:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Owner:");

        tfOwner.setText("jTextField1");

        tfUmurPet.setText("jTextField1");

        tfReservationID1.setText("jTextField1");
        tfReservationID1.addActionListener(this::tfReservationID1ActionPerformed);

        tfService.setText("jTextField1");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Service:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Date:");

        tfDate.setText("jTextField1");
        tfDate.addActionListener(this::tfDateActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfUmurPet, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfReservationID1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfOwner, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfService, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfDate, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(tfOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(tfService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(tfDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(tfUmurPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfReservationID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Diagnosis:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Prescriptions:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Medical Action:");

        jTADiagnosis.setColumns(20);
        jTADiagnosis.setRows(5);
        jTADiagnosis.setText("Enter Diagnosa here...");
        jScrollPane1.setViewportView(jTADiagnosis);

        jTADiagnosis1.setColumns(20);
        jTADiagnosis1.setRows(5);
        jTADiagnosis1.setText("Describde Medical Action taken...");
        jScrollPane2.setViewportView(jTADiagnosis1);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Service Cost");

        tfServiceCost.setText("Masukan Biaya pemeriksaan");
        tfServiceCost.addActionListener(this::tfServiceCostActionPerformed);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setText("Finis Examination");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Cancel");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(595, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(20, 20, 20))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Select Medicine:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Quantity:");

        tfQuantity.setText("1-10");
        tfQuantity.addActionListener(this::tfQuantityActionPerformed);

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tfQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAdd))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 176, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Medicine", "Qty", "Subtotal", "Del"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Total:");

        jLabel13.setText("Service Cost:");

        jLabel14.setText("Mesicines:");

        tfServisCostPerhitungan.setText("0");
        tfServisCostPerhitungan.addActionListener(this::tfServisCostPerhitunganActionPerformed);

        tfMedicines.setText("0");

        tfTotal.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfServisCostPerhitungan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMedicines, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tfServisCostPerhitungan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfMedicines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(208, 208, 208))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfServiceCost, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfServiceCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // ==========================================
    // EVENT: Klik Tombol Delete di Tabel
    // ==========================================
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {
        int row = jTable2.rowAtPoint(evt.getPoint());
        int col = jTable2.columnAtPoint(evt.getPoint());

        if (col == 3) { // Kolom "Del"
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            String namaObat = model.getValueAt(row, 0).toString();
            int qty = Integer.parseInt(model.getValueAt(row, 1).toString());

            // Hapus dari list
            daftarResep.removeIf(d -> ((Obat) d.getObat()).getNamaObat().equals(namaObat) && d.getQty() == qty);

            // Hapus dari tabel
            model.removeRow(row);

            // Recalculate total
            recalculateTotal();
        }
    }
    
    // ==========================================
    // HELPER: Recalculate Total Obat
    // ==========================================
    private void recalculateTotal() {
        totalObat = 0;
        for (DetailTransaksi detail : daftarResep) {
            totalObat += detail.hitungSubtotal();
        }
        updateCostCalculation();
    }
    
    // ==========================================
    // HELPER: Update Cost Calculation Display
    // ==========================================
    private void updateCostCalculation() {
        try {
            double serviceCost = Double.parseDouble(tfServiceCost.getText().trim());
            tfServisCostPerhitungan.setText(formatRupiah(serviceCost));
            tfMedicines.setText(formatRupiah(totalObat));
            double total = serviceCost + totalObat;
            tfTotal.setText(formatRupiah(total));
        } catch (NumberFormatException e) {
            tfServisCostPerhitungan.setText("Rp 0");
            tfMedicines.setText(formatRupiah(totalObat));
            tfTotal.setText(formatRupiah(totalObat));
        }
    }
    // ==========================================
    // EVENT: Text Field Service Cost Changed
    // ==========================================

    
    private void tfReservationID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfReservationID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfReservationID1ActionPerformed

    private void tfDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String diagnosis = jTADiagnosis.getText().trim();
        if (diagnosis.isEmpty() || diagnosis.equals("Enter Diagnosa here...")) {
            JOptionPane.showMessageDialog(this, "Diagnosis tidak boleh kosong!", "Warning", JOptionPane.WARNING_MESSAGE);
            jTADiagnosis.requestFocus();
            return;
        }

        String medicalAction = jTADiagnosis1.getText().trim();
        if (medicalAction.isEmpty() || medicalAction.equals("Describde Medical Action taken...")) {
            JOptionPane.showMessageDialog(this, "Medical action tidak boleh kosong!", "Warning", JOptionPane.WARNING_MESSAGE);
            jTADiagnosis1.requestFocus();
            return;
        }

        double serviceCost;
        try {
            serviceCost = Double.parseDouble(tfServiceCost.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Service cost harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Selesaikan pemeriksaan ini?\nDiagnosis akan disimpan dan status reservasi akan diubah.",
                "Confirm", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                saveExamination(diagnosis, medicalAction, serviceCost);
                JOptionPane.showMessageDialog(this, "Pemeriksaan berhasil diselesaikan!");
                this.dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    // ==========================================
    // LOGIKA: Save Examination ke Database
    // ==========================================
    private void saveExamination(String diagnosis, String medicalAction, double serviceCost) throws SQLException {
        Connection conn = DatabaseConnection.getConnection();
        conn.setAutoCommit(false);

        try {
            int idHewan = 0;
            String sqlGetHewan = "SELECT id_hewan FROM reservasi WHERE id_reservasi = ?";
            PreparedStatement psGetHewan = conn.prepareStatement(sqlGetHewan);
            psGetHewan.setInt(1, idReservasi);
            ResultSet rsGetHewan = psGetHewan.executeQuery();
            if (rsGetHewan.next()) {
                idHewan = rsGetHewan.getInt("id_hewan");
                System.out.println("[DEBUG] ID Hewan: " + idHewan);
            }

            String sqlPemeriksaan = "INSERT INTO pemeriksaan (id_reservasi, id_dokter, diagnosis, tindakan, biaya_layanan, tanggal_periksa) "
                    + "VALUES (?, 1, ?, ?, ?, NOW())";

            PreparedStatement psPemeriksaan = conn.prepareStatement(sqlPemeriksaan, Statement.RETURN_GENERATED_KEYS);
            psPemeriksaan.setInt(1, idReservasi);
            psPemeriksaan.setString(2, diagnosis);
            psPemeriksaan.setString(3, medicalAction);
            psPemeriksaan.setDouble(4, serviceCost);
            psPemeriksaan.executeUpdate();

            ResultSet rs = psPemeriksaan.getGeneratedKeys();
            int idPemeriksaan = 0;
            if (rs.next()) {
                idPemeriksaan = rs.getInt(1);
            }

            System.out.println("[DEBUG] ID Pemeriksaan baru: " + idPemeriksaan);

            String sqlRekamMedis = "INSERT INTO rekam_medis (id_hewan, id_pemeriksaan, riwayat_penyakit) "
                    + "VALUES (?, ?, ?)";
            PreparedStatement psRekam = conn.prepareStatement(sqlRekamMedis);
            psRekam.setInt(1, idHewan);
            psRekam.setInt(2, idPemeriksaan);
            psRekam.setString(3, diagnosis);
            psRekam.executeUpdate();

            System.out.println("[DEBUG] Rekam medis disimpan untuk hewan ID: " + idHewan);

            String sqlDetail = "INSERT INTO detail_transaksi (id_pemeriksaan, id_obat, qty, harga_satuan, subtotal) "
                    + "VALUES (?, ?, ?, ?, ?)";
            PreparedStatement psDetail = conn.prepareStatement(sqlDetail);

            for (DetailTransaksi detail : daftarResep) {
                String namaItem = detail.getNamaItem();
                int qty = detail.getQty();
                double harga = detail.getHargaSatuan();
                double subtotal = detail.hitungSubtotal();

                String sqlGetIdObat = "SELECT id_obat FROM obat WHERE nama_obat = ?";
                PreparedStatement psGetId = conn.prepareStatement(sqlGetIdObat);
                psGetId.setString(1, namaItem);
                ResultSet rsId = psGetId.executeQuery();

                int idObatInt = 0;
                if (rsId.next()) {
                    idObatInt = rsId.getInt("id_obat");
                }

                if (idObatInt > 0) {
                    psDetail.setInt(1, idPemeriksaan);
                    psDetail.setInt(2, idObatInt);
                    psDetail.setInt(3, qty);
                    psDetail.setDouble(4, harga);
                    psDetail.setDouble(5, subtotal);
                    psDetail.addBatch();

                    String sqlUpdateStok = "UPDATE obat SET stok = stok - ? WHERE id_obat = ?";
                    PreparedStatement psUpdateStok = conn.prepareStatement(sqlUpdateStok);
                    psUpdateStok.setInt(1, qty);
                    psUpdateStok.setInt(2, idObatInt);
                    psUpdateStok.executeUpdate();
                }
            }

            psDetail.executeBatch();

            String sqlUpdateStatus = "UPDATE reservasi SET status_reservasi = 'SELESAI' WHERE id_reservasi = ?";
            PreparedStatement psUpdateStatus = conn.prepareStatement(sqlUpdateStatus);
            psUpdateStatus.setInt(1, idReservasi);
            psUpdateStatus.executeUpdate();

            conn.commit();
            System.out.println("[DEBUG] Transaction committed successfully!");

        } catch (SQLException e) {
            conn.rollback();
            System.err.println("[ERROR] Transaction rolled back: " + e.getMessage());
            throw e;
        } finally {
            conn.setAutoCommit(true);
        }
    }
    
    private void tfServiceCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfServiceCostActionPerformed
        // TODO add your handling code here:
        updateCostCalculation();
        
    }//GEN-LAST:event_tfServiceCostActionPerformed

    private void tfServisCostPerhitunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfServisCostPerhitunganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfServisCostPerhitunganActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String selectedItem = (String) jComboBox1.getSelectedItem();

        if (selectedItem == null || selectedItem.equals("-- Pilih Obat --")) {
            JOptionPane.showMessageDialog(this, "Pilih obat terlebih dahulu!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int qty = Integer.parseInt(tfQuantity.getText().trim());
            if (qty <= 0) {
                JOptionPane.showMessageDialog(this, "Quantity harus lebih dari 0!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Parse data dari dropdown
            String[] parts = selectedItem.split("\\|");
            int idObat = Integer.parseInt(parts[0]);
            String[] info = parts[1].split(" - ");
            String namaObat = info[0];

            // Ambil harga dari database
            Connection conn = DatabaseConnection.getConnection();
            String sql = "SELECT harga, stok FROM obat WHERE id_obat = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, idObat);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                double harga = rs.getDouble("harga");
                int stokTersedia = rs.getInt("stok");

                if (qty > stokTersedia) {
                    JOptionPane.showMessageDialog(this, "Stok tidak mencukupi! Tersedia: " + stokTersedia, "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                double subtotal = harga * qty;

                // Tambah ke tabel
                DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                model.addRow(new Object[]{namaObat, qty, formatRupiah(subtotal), "Delete"});

                // ✅ PENTING: Buat DetailTransaksi dengan constructor yang benar
                DetailTransaksi detail = new DetailTransaksi(
                        "DET-" + System.currentTimeMillis(), // ID dummy
                        namaObat, // Nama item
                        qty, // Quantity
                        harga // Harga satuan
                );
                daftarResep.add(detail);

                // Update total
                totalObat += subtotal;
                updateCostCalculation();

                // Clear quantity
                tfQuantity.setText("1");

                JOptionPane.showMessageDialog(this, "Obat berhasil ditambahkan!");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukkan quantity yang valid!", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this,
                "Batal pemeriksaan? Data yang sudah diisi tidak akan disimpan.",
                "Confirm Cancel", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tfQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuantityActionPerformed

    private String formatRupiah(double jumlah) {
        return "Rp " + String.format("%,.0f", jumlah).replace(",", ".");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new FormPemeriksaanFrame(1).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTADiagnosis;
    private javax.swing.JTextArea jTADiagnosis1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField tfDate;
    private javax.swing.JTextField tfMedicines;
    private javax.swing.JTextField tfOwner;
    private javax.swing.JTextField tfQuantity;
    private javax.swing.JTextField tfReservationID1;
    private javax.swing.JTextField tfService;
    private javax.swing.JTextField tfServiceCost;
    private javax.swing.JTextField tfServisCostPerhitungan;
    private javax.swing.JTextField tfTotal;
    private javax.swing.JTextField tfUmurPet;
    // End of variables declaration//GEN-END:variables
}
