/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import database.DatabaseConnection;
import util.SessionManager;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Customer;
import model.DetailTransaksi;
import model.Hewan;
import model.Reservasi;
import model.Tagihan;
/**
 *
 * @author Dit
 */
public class StaffDashboardFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StaffDashboardFrame.class.getName());

    /**
     * Creates new form StaffDashboardFrame
     */
    public StaffDashboardFrame() {
        initComponents();
        setLocationRelativeTo(null);  
        loadReservasiData();           // Load data dari database
        loadCashierQueue();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnAssignToDoctor = new javax.swing.JButton();
        btnConfirmChechIn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel = new javax.swing.JLabel();
        btnProcessPayment = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane1.setAlignmentX(1.0F);
        jTabbedPane1.setAlignmentY(1.0F);
        jTabbedPane1.addChangeListener(this::jTabbedPane1StateChanged);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Res, ID", "Owner Name", "Pet", "Service", "Date", "Time", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField1.setText("serch by owner");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jButton1.setText("Clear");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        btnAssignToDoctor.setText("Assign To Doctor");
        btnAssignToDoctor.addActionListener(this::btnAssignToDoctorActionPerformed);

        btnConfirmChechIn.setText("Confirm Chech-in");
        btnConfirmChechIn.addActionListener(this::btnConfirmChechInActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnConfirmChechIn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAssignToDoctor)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 985, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 19, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmChechIn)
                    .addComponent(btnAssignToDoctor))
                .addGap(0, 28, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Chech-in Queue", jPanel2);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Res, ID", "Owner Name", "Pet", "Service", "Date", "Total Cost"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel.setText("Reservation ready for payment (Status: DONE)");

        btnProcessPayment.setText("Process Payment");
        btnProcessPayment.addActionListener(this::btnProcessPaymentActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProcessPayment)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProcessPayment)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cashier", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Medicine Stok", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Financial Report", jPanel5);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Dashboard Administrasi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(670, 670, 670)
                .addComponent(btnLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1014, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnAssignToDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToDoctorActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih reservasi terlebih dahulu!",
                    "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String resId = jTable1.getValueAt(selectedRow, 0).toString();
        int idReservasi = Integer.parseInt(resId.replace("R-", ""));

        // Dialog pilih dokter
        String[] doctors = {
            "Dr. Andi Wijaya - Umum",
            "Dr. Budi Santoso - Bedah",
            "Dr. Cindy Lestari - Penyakit Dalam",
            "Dr. Dedi Kurniawan - Eksotik"
        };

        String selectedDoctor = (String) JOptionPane.showInputDialog(
                this,
                "Pilih dokter untuk reservasi " + resId + ":",
                "Assign Doctor",
                JOptionPane.QUESTION_MESSAGE,
                null,
                doctors,
                doctors[0]
        );

        if (selectedDoctor != null) {
            try {
                Connection conn = DatabaseConnection.getConnection();
                String sql = "UPDATE reservasi SET status_reservasi = 'ASSIGNED' WHERE id_reservasi = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setInt(1, idReservasi);
                ps.executeUpdate();

                JOptionPane.showMessageDialog(this,
                        "Reservasi " + resId + " berhasil diassign ke " + selectedDoctor);
                loadReservasiData();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnAssignToDoctorActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        String keyword = jTextField1.getText().trim();
        if (!keyword.isEmpty() && !keyword.equals("serch by owner")) {
            searchReservasi(keyword);
        } else {
            loadReservasiData();
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        loadReservasiData();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnConfirmChechInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmChechInActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih reservasi terlebih dahulu!",
                    "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String resId = jTable1.getValueAt(selectedRow, 0).toString();
        int idReservasi = Integer.parseInt(resId.replace("R-", ""));

        try {
            Connection conn = DatabaseConnection.getConnection();
            String sql = "UPDATE reservasi SET status_reservasi = 'CHECK_IN' WHERE id_reservasi = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, idReservasi);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Check-In berhasil untuk reservasi: " + resId);
            loadReservasiData();  // Refresh tabel

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnConfirmChechInActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        SessionManager.getInstance().logout();
        JOptionPane.showMessageDialog(this, "Anda telah logout!");
        this.dispose();
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnProcessPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessPaymentActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable2.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih reservasi terlebih dahulu!");
            return;
        }

        String resId = jTable2.getValueAt(selectedRow, 0).toString();
        int idReservasi = Integer.parseInt(resId.replace("R-", ""));

        Tagihan tagihan = loadTagihanFromDatabase(idReservasi);

        if (tagihan == null) {
            JOptionPane.showMessageDialog(this, "Data tagihan tidak ditemukan!");
            return;
        }

        FormPembayaranFrame form = new FormPembayaranFrame(tagihan);
        form.setLocationRelativeTo(this);

        form.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                System.out.println("[DEBUG] Payment form closed, refreshing cashier data...");
                loadCashierQueue();  
            }
        });

        form.setVisible(true);
    }//GEN-LAST:event_btnProcessPaymentActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        int selectedIndex = jTabbedPane1.getSelectedIndex();
        String selectedTitle = jTabbedPane1.getTitleAt(selectedIndex);

        if (selectedTitle.equals("Finance") || selectedTitle.equals("Financial Report")) {
            JOptionPane.showMessageDialog(this,
                    "Fitur " + selectedTitle + " akan datang nanti!!\n\n"
                    + "Fitur ini sedang dalam pengembangan.",
                    "Coming Soon",
                    JOptionPane.INFORMATION_MESSAGE);

            // Kembalikan ke tab Check-in Queue (index 0)
            jTabbedPane1.setSelectedIndex(0);
        }
        else if (selectedTitle.equals("Medicine Stok") || selectedTitle.equals("Medicine Stock")) {
            JOptionPane.showMessageDialog(this,
                    "Fitur Medicine Stok akan datang nanti!\n\n"
                    + "Fitur ini sedang dalam pengembangan.\n"
                    + "Terima kasih atas kesabarannya!",
                    "Coming Soon",
                    JOptionPane.INFORMATION_MESSAGE);

            // Kembalikan ke tab Check-in Queue (index 0)
            jTabbedPane1.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void loadReservasiData() {
        try {
            Connection conn = DatabaseConnection.getConnection();

            // Query TANPA kolom jenis
            String sql = "SELECT r.id_reservasi, u.nama_lengkap, h.nama_hewan, "
                    + "r.tanggal, r.status_reservasi "
                    + "FROM reservasi r "
                    + "INNER JOIN hewan h ON r.id_hewan = h.id_hewan "
                    + "INNER JOIN customer c ON r.id_customer = c.id_customer "
                    + "INNER JOIN users u ON c.id_user = u.id_user "
                    + "ORDER BY r.tanggal DESC";

            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            DefaultTableModel model = new DefaultTableModel(
                    new String[]{"Res. ID", "Owner Name", "Pet", "Service", "Date", "Time", "Status"}, 0
            );

            while (rs.next()) {
                String tanggal = rs.getString("tanggal");
                String[] parts = tanggal != null ? tanggal.split(" ") : new String[]{"-", "-"};

                model.addRow(new Object[]{
                    "R-" + rs.getInt("id_reservasi"),
                    rs.getString("nama_lengkap"),
                    rs.getString("nama_hewan"), 
                    "General Checkup",
                    parts.length > 0 ? parts[0] : "-",
                    parts.length > 1 ? parts[1] : "-",
                    rs.getString("status_reservasi")
                });
            }

            jTable1.setModel(model);

        } catch (Exception e) {
            System.err.println("[ERROR] " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage());
        }
    }
    
    private Tagihan loadTagihanFromDatabase(int idReservasi) {
        try {
            Connection conn = DatabaseConnection.getConnection();

            // QUERY 1: Ambil data reservasi
            String sqlReservasi = "SELECT r.id_reservasi, r.tanggal, r.status_reservasi, "
                    + "h.id_hewan, h.nama_hewan, h.jenis, h.umur, "
                    + "c.id_customer, u.nama_lengkap "
                    + "FROM reservasi r "
                    + "JOIN hewan h ON r.id_hewan = h.id_hewan "
                    + "JOIN customer c ON r.id_customer = c.id_customer "
                    + "JOIN users u ON c.id_user = u.id_user "
                    + "WHERE r.id_reservasi = ?";

            PreparedStatement psRes = conn.prepareStatement(sqlReservasi);
            psRes.setInt(1, idReservasi);
            ResultSet rsRes = psRes.executeQuery();

            if (rsRes.next()) {
                Customer customer = new Customer("", "", "", "", rsRes.getString("nama_lengkap"));
                customer.setIdCustomer(rsRes.getInt("id_customer"));

                Hewan hewan = new Hewan(
                        rsRes.getInt("id_hewan"),
                        rsRes.getString("nama_hewan"),
                        rsRes.getString("jenis"),
                        rsRes.getInt("umur"),
                        rsRes.getInt("id_customer")
                );
                hewan.setPemilik(customer);

                Reservasi reservasi = new Reservasi(
                        String.valueOf(idReservasi),
                        customer,
                        hewan,
                        rsRes.getTimestamp("tanggal"),
                        rsRes.getString("status_reservasi")
                );

                Tagihan tagihan = new Tagihan(idReservasi, reservasi);

                // QUERY 2: Ambil detail transaksi
                String sqlDetail = "SELECT o.nama_obat as nama_item, "
                        + "dt.qty, dt.harga_satuan, dt.subtotal "
                        + "FROM detail_transaksi dt "
                        + "INNER JOIN obat o ON dt.id_obat = o.id_obat "
                        + "WHERE dt.id_pemeriksaan IN ("
                        + "  SELECT id_pemeriksaan FROM pemeriksaan WHERE id_reservasi = ?"
                        + ")";

                System.out.println("Query detail: " + sqlDetail);
                System.out.println("Parameter: " + idReservasi);

                PreparedStatement psDetail = conn.prepareStatement(sqlDetail);
                psDetail.setInt(1, idReservasi);
                ResultSet rsDetail = psDetail.executeQuery();

                int count = 0;
                while (rsDetail.next()) {
                    count++;
                    System.out.println("Detail ke-" + count + ": " + rsDetail.getString("nama_item"));

                    DetailTransaksi detail = new DetailTransaksi(
                            "DET-" + count,
                            rsDetail.getString("nama_item"),
                            rsDetail.getInt("qty"),
                            rsDetail.getDouble("harga_satuan")
                    );
                    tagihan.tambahDetail(detail);
                }

                System.out.println("Total detail loaded: " + count);

                return tagihan;
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        return null;
    }
    
// 🔹 Search reservasi berdasarkan nama owner atau nama hewan
    private void searchReservasi(String keyword) {
        try {
            Connection conn = DatabaseConnection.getConnection();

            String sql = "SELECT "
                    + "r.id_reservasi, "
                    + "h.nama_hewan, "
                    + "p.biaya_layanan, "
                    + "(SELECT SUM(dt.subtotal) FROM detail_transaksi dt WHERE dt.id_pemeriksaan = p.id_pemeriksaan) as total_obat, "
                    + "(COALESCE(p.biaya_layanan, 0) + COALESCE((SELECT SUM(dt.subtotal) FROM detail_transaksi dt WHERE dt.id_pemeriksaan = p.id_pemeriksaan), 0)) as total_cost "
                    + "FROM reservasi r "
                    + "JOIN hewan h ON r.id_hewan = h.id_hewan "
                    + "LEFT JOIN pemeriksaan p ON r.id_reservasi = p.id_reservasi "
                    + "WHERE r.status_reservasi IN ('SELESAI', 'DONE') "
                    + "ORDER BY r.tanggal DESC";

            System.out.println("[DEBUG] Query Cashier: " + sql);

            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                int idReservasi = rs.getInt("id_reservasi");
                String namaHewan = rs.getString("nama_hewan");
                double biayaLayanan = rs.getDouble("biaya_layanan");
                double totalObat = rs.getDouble("total_obat");
                double totalCost = rs.getDouble("total_cost");

                System.out.println("[DEBUG] R-" + idReservasi + " | " + namaHewan
                        + " | Biaya: " + biayaLayanan
                        + " | Obat: " + totalObat
                        + " | TOTAL: " + totalCost);

                String namaOwner = "";
                String sqlOwner = "SELECT u.nama_lengkap FROM users u "
                        + "JOIN customer c ON u.id_user = c.id_user "
                        + "WHERE c.id_customer = (SELECT id_customer FROM reservasi WHERE id_reservasi = ?)";
                PreparedStatement psOwner = conn.prepareStatement(sqlOwner);
                psOwner.setInt(1, idReservasi);
                ResultSet rsOwner = psOwner.executeQuery();
                if (rsOwner.next()) {
                    namaOwner = rsOwner.getString("nama_lengkap");
                }

                model.addRow(new Object[]{
                    "R-" + idReservasi,
                    namaOwner,
                    namaHewan,
                    "General Checkup",
                    rs.getString("tanggal") != null ? rs.getString("tanggal").split(" ")[0] : "-",
                    "Rp " + String.format("%,.0f", totalCost).replace(",", ".")
                });
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading cashier data: " + e.getMessage());
        }
    }
    
    private void loadCashierQueue() {
        try {
            Connection conn = DatabaseConnection.getConnection();

            String sql = "SELECT "
                    + "r.id_reservasi, "
                    + "u.nama_lengkap, "
                    + "h.nama_hewan, "
                    + "GROUP_CONCAT(l.nama_layanan SEPARATOR ', ') as layanan, "
                    + "DATE(r.tanggal) as tanggal, "
                    + "TIME(r.tanggal) as waktu, "
                    + "(COALESCE((SELECT SUM(rl.harga_satuan) FROM reservasi_layanan rl WHERE rl.id_reservasi = r.id_reservasi), 0) "
                    + "+ COALESCE(p.biaya_layanan, 0) "
                    + "+ COALESCE((SELECT SUM(dt.subtotal) FROM detail_transaksi dt WHERE dt.id_pemeriksaan = p.id_pemeriksaan), 0)) as total_cost, "
                    + "r.status_reservasi "
                    + "FROM reservasi r "
                    + "JOIN hewan h ON r.id_hewan = h.id_hewan "
                    + "JOIN customer c ON r.id_customer = c.id_customer "
                    + "JOIN users u ON c.id_user = u.id_user "
                    + "LEFT JOIN pemeriksaan p ON r.id_reservasi = p.id_reservasi "
                    + "LEFT JOIN reservasi_layanan rl ON r.id_reservasi = rl.id_reservasi "
                    + "LEFT JOIN layanan l ON rl.id_layanan = l.id_layanan "
                    + "WHERE r.status_reservasi IN ('SELESAI', 'DONE') "
                    + "GROUP BY r.id_reservasi, u.nama_lengkap, h.nama_hewan, DATE(r.tanggal), TIME(r.tanggal), p.biaya_layanan, r.status_reservasi "
                    + "ORDER BY r.tanggal DESC";

            System.out.println("[DEBUG] Query Cashier: " + sql);

            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                int idReservasi = rs.getInt("id_reservasi");
                String namaOwner = rs.getString("nama_lengkap");
                String namaHewan = rs.getString("nama_hewan");
                String layanan = rs.getString("layanan");
                String tanggal = rs.getString("tanggal");
                String waktu = rs.getString("waktu");
                double totalCost = rs.getDouble("total_cost");

                if (layanan == null || layanan.isEmpty()) {
                    layanan = "General Checkup";
                }

                System.out.println("[DEBUG] R-" + idReservasi + " | " + namaHewan + " | " + layanan + " | Total: " + totalCost);

                model.addRow(new Object[]{
                    "R-" + idReservasi,
                    namaOwner,
                    namaHewan,
                    layanan, 
                    tanggal,
                    waktu,
                    "Rp " + String.format("%,.0f", totalCost).replace(",", ".")
                });
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading cashier data: " + e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StaffDashboardFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignToDoctor;
    private javax.swing.JButton btnConfirmChechIn;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnProcessPayment;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
